// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDymSlVbAQTZ7WJf5-sq2ntlNr93I3ev9A',
    appId: '1:142583978232:web:8ee974fb734286ead2030d',
    messagingSenderId: '142583978232',
    projectId: 'flutter-firebase-auth-68109',
    authDomain: 'flutter-firebase-auth-68109.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-68109.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4X5YqXJTEzAHQw7utmTfJfDIwBOHyqz0',
    appId: '1:142583978232:android:619648b4078cfeccd2030d',
    messagingSenderId: '142583978232',
    projectId: 'flutter-firebase-auth-68109',
    storageBucket: 'flutter-firebase-auth-68109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFKzoN-cOTFzHof9liygLSjEuZwYRfcF4',
    appId: '1:142583978232:ios:f6aa68adcf6be6aad2030d',
    messagingSenderId: '142583978232',
    projectId: 'flutter-firebase-auth-68109',
    storageBucket: 'flutter-firebase-auth-68109.appspot.com',
    androidClientId: '142583978232-c76cbdtak0tjrh5t2epkcnij4m497i3n.apps.googleusercontent.com',
    iosClientId: '142583978232-4tuqjplft0ubjv19ku9vcoui0a4lp8q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
